name: Integration Test CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, 'dependabot/*']

jobs:
    JavaScript:
        runs-on: ubuntu-latest
        env:
            APP: 'loading-icons-tester-js'
            CLIENT: 'react-loading-icons'
            WORKDIR: '/home/runner/work/react-loading-icons/react-loading-icons'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '16'
                  check-latest: true

            - name: Create React App
              run: >-
                  npx create-react-app ${{env.APP}} &&
                  cd ${{env.APP}} &&
                  npm install react-loading-icons

            - name: Build latest client
              run: >-
                  cd $WORKDIR &&
                  npm install &&
                  npm run build &&
                  npm link

            - name: Build with latest client
              run: >-
                  cd ${{env.APP}} &&
                  npm link react-loading-icons &&
                  npm install &&
                  npm run build

    TypeScript:
        runs-on: ubuntu-latest
        env:
            APP: 'loading-icons-tester-ts'
            CLIENT: 'react-loading-icons'
            WORKDIR: '/home/runner/work/react-loading-icons/react-loading-icons'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '16'
                  check-latest: true

            - name: Create React App
              run: >-
                  npx create-react-app ${{env.APP}} --template typescript &&
                  cd ${{env.APP}} &&
                  npm install react-loading-icons

            - name: Build latest client
              run: >-
                  cd $WORKDIR &&
                  npm install &&
                  npm run build

            - name: Build app with latest client
              run: >-
                  cd ${{env.APP}} &&
                  npm link react-loading-icons &&
                  npm install &&
                  npm run build