name: Integration Test CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, 'dependabot/*']

jobs:
    JavaScript:
        runs-on: ubuntu-latest
        env:
            LIT: 'loading-icons-tester-js'
            RLI: 'react-loading-icons'
            WORKDIR: '/home/runner/work/react-loading-icons/react-loading-icons'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '15'
                  check-latest: true

            - name: Create React App
              run: >-
                  npx create-react-app ${{env.LIT}} &&
                  cd ${{env.LIT}} &&
                  yarn &&
                  yarn add wordpress-api-client

            - name: Install Dependencies
              run: >-
                  cd $WORKDIR &&
                  yarn &&
                  yarn build

            - name: Build with linked Module
              run: >-
                  cd ${{env.LIT}} &&
                  yarn link $WORKDIR &&
                  yarn build

    TypeScript:
        runs-on: ubuntu-latest
        env:
            LIT: 'loading-icons-tester-ts'
            RLI: 'react-loading-icons'
            WORKDIR: '/home/runner/work/react-loading-icons/react-loading-icons'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '15'
                  check-latest: true

            - name: Create React App
              run: >-
                  npx create-react-app ${{env.LIT}} --template typescript &&
                  cd ${{env.LIT}} &&
                  yarn &&
                  yarn add wordpress-api-client

            - name: Install Dependencies
              run: >-
                  cd $WORKDIR &&
                  yarn &&
                  yarn build

            - name: Build with linked Module
              run: >-
                  cd ${{env.LIT}} &&
                  yarn link $WORKDIR &&
                  yarn &&
                  yarn build