name: Unit Test CI

on:
    push:
        branches: [master, feature/workflow]
    pull_request:
        branches: [master, 'dependabot/*']

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
            - run: yarn coverage
    
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Share Test Coverage
              uses: actions/setup-node@v1
              with:
                  node-version: '15'
            - run: yarn global add codecov
            - run: yarn
            - run: yarn coverage
            - run: codecov
