name: Unit Test CI

on:
    push:
        branches: [master, feature/workflow]
    pull_request:
        branches: [master, 'dependabot/*']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
            - run: yarn test
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - run: yarn global add codecov
            - run: yarn
            - run: yarn build
            - run: yarn coverage
            - run: yarn codecov
